server{
        #adicionar em server_name o IP do Portainer ou o hostname caso funcione com certificado
        server_name IP_do_Portainer_hostname;
        listen 9000;
#        ssl_certificate caminho/do/certificado/certificado.crt;
#        ssl_certificate_key caminho/do/certificado/certificado.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers ALL:!RSA:!CAMELLIA:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4:!SHA1:!SHA256:!SHA384;
#        ssl_stapling_verify on;

        location / {
                add_header X-Frame-Options DENY always;
                add_header X-Content-Type-Options nosniff always;
                add_header X-Permitted-Cross-Domain-Policies "none" always;
                add_header X-XSS-Protection "1; mode=block" always;
                add_header Referrer-Policy "no-referrer" always;
                add_header "Pragma" "no-cache" always;
                add_header Cache-Control "max-age=0, no-cache, public, no-transform" always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
                add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload" always;
                add_header Set-Cookie "Path=/; HttpOnly; Secure" always;
                proxy_pass http://portainer;
        }
}

upstream portainer {
        server portainer:9000;
}